version: '3'
services:
  kvix-server:
    container_name: kvix-server
    restart: always
    build: .
    image: cassianokunsch/kvix-store-server
    volumes:
      - './:/release'
    ports:
      - '3000:3000'
    environment:
      APP_SECRET: $APP_SECRET
      NODE_ENV: $NODE_ENV
      DIALECT: $DIALECT
      HOST: $HOST
      USERNAME: $USERNAME
      PASSWORD: $PASSWORD
      DATABASE: $DATABASE
      PORT: $PORT
      SYNCHRONIZE: $SYNCHRONIZE
      AUTOLOADMODELS: $AUTOLOADMODELS
    depends_on:
      - kvix-db
  kvix-db:
    image: 'postgres:12.2-alpine'
    container_name: kvix-db
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DATABASE
      POSTGRES_USER: $USERNAME
      POSTGRES_PASSWORD: $PASSWORD
  kvix-pgadmin:
    image: dpage/pgadmin4
    container_name: kvix-pgadmin
    restart: always
    depends_on:
      - kvix-db
    ports:
      - '80:80'
    volumes:
      - /var/lib/pgadmin
      - /pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin
