version: '3'
services:
  # Backend
  kvix-server:
    build: .
    restart: always

    volumes:
      - './:/kvix'
    ports:
      - '4000'
    environment:
      NODE_ENV: development
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: kvix-db
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: kvix
      TYPEORM_DATABASE: postgres
      TYPEORM_PORT: 5432
      TYPEORM_SYNCHRONIZE: 'true'
      TYPEORM_LOGGING: 'true'
      TYPEORM_ENTITIES: src/modules/**/entity/*.ts
    depends_on:
      - kvix-db

  # Postgres Dev Database
  kvix-db:
    image: postgres:11.3-alpine
    container_name: kvix-db

    ports:
      - '5432'
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: kvix

  # PgAdmin4
  kvix-pgadmin:
    image: dpage/pgadmin4
    container_name: kvix-pgadmin
    restart: always

    depends_on:
      - kvix-db
    ports:
      - '80:80'
    volumes:
      - /var/lib/pgadmin
      - /pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin
